export const XpsDbColumns = [
  { tableId: 1, columnName: "Test Column" },
  { tableId: 1, columnName: "User ID" },
  { tableId: 1, columnName: "Username" },
  { tableId: 1, columnName: "Email Address" },
  { tableId: 1, columnName: "First Name" },
  { tableId: 1, columnName: "Last Name" },
  { tableId: 1, columnName: "Created Date" },
  { tableId: 1, columnName: "Last Login" },
  { tableId: 2, columnName: "Product ID" },
  { tableId: 2, columnName: "Product Name" },
  { tableId: 2, columnName: "Description" },
  { tableId: 2, columnName: "Price" },
  { tableId: 2, columnName: "Category" },
  { tableId: 2, columnName: "Stock Quantity" },
  { tableId: 2, columnName: "SKU" },
  { tableId: 3, columnName: "Order ID" },
  { tableId: 3, columnName: "Customer ID" },
  { tableId: 3, columnName: "Order Date" },
  { tableId: 3, columnName: "Total Amount" },
  { tableId: 3, columnName: "Status" },
  { tableId: 3, columnName: "Shipping Address" },
  { tableId: 4, columnName: "Task ID" },
  { tableId: 4, columnName: "Task Name" },
  { tableId: 4, columnName: "Description" },
  { tableId: 4, columnName: "Priority" },
  { tableId: 4, columnName: "Assigned To" },
  { tableId: 4, columnName: "Due Date" },
  { tableId: 4, columnName: "Status" },
  { tableId: 5, columnName: "Log ID" },
  { tableId: 5, columnName: "Timestamp" },
];
