export const xpsTablesSeed = [
  { tableName: "User Authentication Tests" },
  { tableName: "Login Functionality Tests" },
  { tableName: "Password Reset Tests" },
  { tableName: "User Registration Tests" },
  { tableName: "Profile Management Tests" },
  { tableName: "Dashboard Navigation Tests" },
  { tableName: "API Endpoint Tests" },
  { tableName: "Database Connection Tests" },
  { tableName: "File Upload Tests" },
  { tableName: "Form Validation Tests" },
  { tableName: "Security Authorization Tests" },
  { tableName: "Payment Processing Tests" },
  { tableName: "Email Notification Tests" },
  { tableName: "Search Functionality Tests" },
  { tableName: "Data Export Tests" },
  { tableName: "Mobile Responsiveness Tests" },
  { tableName: "Cross Browser Tests" },
  { tableName: "Performance Load Tests" },
  { tableName: "Error Handling Tests" },
  { tableName: "Session Management Tests" },
  { tableName: "Report Generation Tests" },
  { tableName: "Backup Recovery Tests" },
  { tableName: "Integration API Tests" },
  { tableName: "UI Component Tests" },
  { tableName: "Data Validation Tests" },
  { tableName: "User Role Tests" },
  { tableName: "Notification System Tests" },
  { tableName: "Cache Management Tests" },
  { tableName: "Logging System Tests" },
  { tableName: "Configuration Tests" },
];
