export const XpsMenuSeedData = [
  { menuName: "Dashboard", schemeLevel: "ML", module: "Details" },
  { menuName: "Transactions", schemeLevel: "SL", module: "Reports" },
  { menuName: "Invoices", schemeLevel: "TL", module: "Letters" },
  { menuName: "Budgets", schemeLevel: "ML", module: "ToolsAndProcess" },
  { menuName: "Accounts", schemeLevel: "SL", module: "Details" },
  { menuName: "Analytics", schemeLevel: "TL", module: "Reports" },
  { menuName: "Settings", schemeLevel: "ML", module: "ToolsAndProcess" },
  { menuName: "Notifications", schemeLevel: "SL", module: "Letters" },
  { menuName: "Approvals", schemeLevel: "TL", module: "Details" },
  { menuName: "Audit Trail", schemeLevel: "ML", module: "Reports" },
  { menuName: "Payroll", schemeLevel: "SL", module: "Letters" },
  { menuName: "Vendors", schemeLevel: "TL", module: "ToolsAndProcess" },
  { menuName: "Receipts", schemeLevel: "ML", module: "Details" },
  { menuName: "Expenses", schemeLevel: "SL", module: "Reports" },
  { menuName: "Assets", schemeLevel: "TL", module: "Letters" },
  { menuName: "Loans", schemeLevel: "ML", module: "ToolsAndProcess" },
  { menuName: "Tax", schemeLevel: "SL", module: "Details" },
  { menuName: "Statements", schemeLevel: "TL", module: "Reports" },
  { menuName: "Forecast", schemeLevel: "ML", module: "Letters" },
  { menuName: "Reconciliation", schemeLevel: "SL", module: "ToolsAndProcess" },
];
