export const portalsList = [
  {
    portalName: "XPS",
    appName: "PenScope",
    userName: "john.doe",
    password: "password123",
    memorableWord: "WhatAMemorableWord",
    portalUrl: "https://xps.example.com",
  },
  {
    portalName: "EMember",
    appName: "Admin",
    userName: "emma.smith",
    password: "securePass!",
    memorableWord: "FirstPet",
    portalUrl: "https://emember-admin.example.com",
  },
  {
    portalName: "Default",
    appName: "Cat",
    userName: "alex.jones",
    password: "defaultPass",
    memorableWord: "FavoriteColor",
    portalUrl: "https://default-cat.example.com",
  },
  {
    portalName: "XPS",
    appName: "Reports",
    userName: "maria.garcia",
    password: "report@2024",
    memorableWord: "DreamCar",
    portalUrl: "https://xps-reports.example.com",
  },
  {
    portalName: "EMember",
    appName: "CatUmbraco",
    userName: "david.wilson",
    password: "umbracoPass",
    memorableWord: "BestFriend",
    portalUrl: "https://emember-cat-umbraco.example.com",
  },
  {
    portalName: "Default",
    appName: "ToolsAndProcess",
    userName: "sophia.taylor",
    password: "tools1234",
    memorableWord: "MotherMaidenName",
    portalUrl: "https://default-tools.example.com",
  },
  {
    portalName: "XPS",
    appName: "Leavers",
    userName: "liam.martin",
    password: "leave!pass",
    memorableWord: "HighSchool",
    portalUrl: "https://xps-leavers.example.com",
  },
  {
    portalName: "EMember",
    appName: "Public",
    userName: "olivia.brown",
    password: "publicPortal",
    memorableWord: "FavoriteFood",
    portalUrl: "https://emember-public.example.com",
  },
  {
    portalName: "Default",
    appName: "Letters",
    userName: "will.johnson",
    password: "letters#2024",
    memorableWord: "VacationSpot",
    portalUrl: "https://default-letters.example.com",
  },
  {
    portalName: "XPS",
    appName: "Details",
    userName: "ava.davis",
    password: "detailsSecure",
    memorableWord: "ChildhoodHero",
    portalUrl: "https://xps-details.example.com",
  },
];
