export const EmMenuSeedData = [
  { menuName: "Overview", portalName: "Public" },
  { menuName: "Accounts", portalName: "Admin" },
  { menuName: "Transactions", portalName: "Cat" },
  { menuName: "Budgets", portalName: "CatUmbraco" },
  { menuName: "Reports", portalName: "Umbraco" },
  { menuName: "Analytics", portalName: "Public" },
  { menuName: "Invoices", portalName: "Admin" },
  { menuName: "Payments", portalName: "Cat" },
  { menuName: "Expenses", portalName: "CatUmbraco" },
  { menuName: "Revenue", portalName: "Umbraco" },
  { menuName: "Forecast", portalName: "Public" },
  { menuName: "Assets", portalName: "Admin" },
  { menuName: "Liabilities", portalName: "Cat" },
  { menuName: "Balance Sheet", portalName: "CatUmbraco" },
  { menuName: "Profit & Loss", portalName: "Umbraco" },
  { menuName: "Cash Flow", portalName: "Public" },
  { menuName: "Tax", portalName: "Admin" },
  { menuName: "Audit", portalName: "Cat" },
  { menuName: "Settings", portalName: "CatUmbraco" },
  { menuName: "Notifications", portalName: "Umbraco" },
];
